#!/bin/bash

set -e

# This release script assumes that you have codekitchen/homebrew-pipeline checked
# out as a sibling to this pipeline checkout.

VERSION=$1
TODAY=$(date "+%Y-%m-%d")
TARBALL=pipeline-$version.tar.gz

: ${VERSION:?"Need to specify a version e.g. 2.0.1"}

sed -i '' $'s/## \[Unreleased\]/## \[Unreleased\]\
\
## '"[$VERSION] - $TODAY/g" CHANGELOG.md

git commit -am "v$VERSION"
git tag "v$VERSION"
REF=$(git show-ref -s "v$VERSION")

rm pipeline-*.tar.gz
make dist
SHA256=$(shasum -a 256 $TARBALL|awk '{print $1}')

pushd ../homebrew-pipeline
sed -i '' 's|  url ".*releases.*|  url "https://github.com/codekitchen/pipeline/releases/download/v'$VERSION'/'$TARBALL'"|' pipeline.rb
sed -i '' 's|  sha256 ".*|  sha256 "'$SHA256'"|' pipeline.rb
git commit -am "release v$VERSION"
popd

read -p "Press [Enter] to continue release..."

git push origin master:master
git push origin "v$VERSION"

hub release create -o -a $TARBALL "v$VERSION"

pushd ../homebrew-pipeline
git push origin master:master
popd
